server:
  port: 7000

spring:
  application:
    name: API-GATEWAY
  zipkin:
    base-url: http://127.0.0.1:9411/
  management:
    tracing:
      sampling:
        probability: 1.0
  cloud:
    gateway:
      routes:
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**
          filters:
            - name: CircuitBreaker
              args:
                name: CUSTOMER-SERVICE
                fallbackuri: forward:/fall-back/customer-service
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: PRODUCT-SERVICE
                fallbackuri: forward:/fall-back/product-service
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: ORDER-SERVICE
                fallbackuri: forward:/fall-back/order-service
#hystrix:
#  command:
#    fallbackcmd:
#      execution:
#        isolation:
#          thread:
#            timeoutInMillisecond: 3000
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream

management:
  endpoints:
    web:
      exposure:
        include: "*"
